/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:8ff288ea-b821-456b-b6c5-d1e4530574a0',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_ppzp9mXz6',
  aws_user_pools_web_client_id: '1lln175c1fjcsj8dk7k0t0kood',
  oauth: {
    domain: 'pxboost-pxboost.auth.us-east-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: 'pxboost://pxboost',
    redirectSignOut: 'pxboost://pxboost',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
};

export default awsmobile;
